-- OTOİZ 04A-S — safe schema baseline, part 5/5
-- Staging ONLY (ctltjunojlaanzurxpzy / akilli-servis-anahtari-staging).
-- NOTE: as-applied historical record (Production's grant matrix at
-- baseline time, including the over-broad TRUNCATE/TRIGGER/REFERENCES
-- and anon base-table grants). Narrowed by migration
-- 20260922180400_grant_tightening.sql — do not edit this file to "fix" it.

-- Table grants: replicate Production's exact anon/authenticated/service_role matrix.
-- Standard set (DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE) on 10 tables.
grant delete, insert, references, select, trigger, truncate, update on public.audit_log to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.customers to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.data_deletion_requests to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.kvkk_consents to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.maintenance_items to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.maintenance_records to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.ownership_transfers to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.qr_keys to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.staff_users to anon, authenticated, service_role;
grant delete, insert, references, select, trigger, truncate, update on public.vehicles to anon, authenticated, service_role;

-- tenants: Production exception — anon does NOT have table-level SELECT (only authenticated/service_role do)
grant delete, insert, references, trigger, truncate, update on public.tenants to anon;
grant delete, insert, references, select, trigger, truncate, update on public.tenants to authenticated, service_role;

-- Function EXECUTE grants: revoke the PostgreSQL default (PUBLIC) then grant exactly as observed on Production.
revoke all on function public.accept_ownership_transfer(text) from public;
grant execute on function public.accept_ownership_transfer(text) to authenticated, service_role;

revoke all on function public.cancel_ownership_transfer(text) from public;
grant execute on function public.cancel_ownership_transfer(text) to authenticated, service_role;

revoke all on function public.get_public_vehicle_passport(text) from public;
grant execute on function public.get_public_vehicle_passport(text) to anon, authenticated, service_role;

revoke all on function public.initiate_ownership_transfer(uuid) from public;
grant execute on function public.initiate_ownership_transfer(uuid) to authenticated, service_role;

revoke all on function public.list_my_pending_outgoing_transfers() from public;
grant execute on function public.list_my_pending_outgoing_transfers() to authenticated, service_role;

revoke all on function public.log_ownership_transfer() from public;
grant execute on function public.log_ownership_transfer() to service_role;

revoke all on function public.log_qr_key_assigned() from public;
grant execute on function public.log_qr_key_assigned() to service_role;

revoke all on function public.log_qr_key_revoked() from public;
grant execute on function public.log_qr_key_revoked() to service_role;

revoke all on function public.log_vehicle_created() from public;
grant execute on function public.log_vehicle_created() to service_role;

revoke all on function public.preview_ownership_transfer(text) from public;
grant execute on function public.preview_ownership_transfer(text) to anon, authenticated, service_role;
